/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huami_watch_opus_OpusCodecEncoder */

#ifndef _Included_com_huami_watch_opus_OpusCodecEncoder
#define _Included_com_huami_watch_opus_OpusCodecEncoder
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_huami_watch_opus_OpusCodecEncoder
 * Method:    opusEncodeCreate
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_huami_watch_opus_OpusCodecEncoder_opusEncodeCreate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_huami_watch_opus_OpusCodecEncoder
 * Method:    opusEncoderGetSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_huami_watch_opus_OpusCodecEncoder_opusEncoderGetSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_huami_watch_opus_OpusCodecEncoder
 * Method:    opusEncoderInit
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_huami_watch_opus_OpusCodecEncoder_opusEncoderInit
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_huami_watch_opus_OpusCodecEncoder
 * Method:    opusIntOpusEncode
 * Signature: ([BFI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_huami_watch_opus_OpusCodecEncoder_opusIntOpusEncode
        (JNIEnv *, jobject, jbyteArray, jfloat, jint);

/*
 * Class:     com_huami_watch_opus_OpusCodecEncoder
 * Method:    opusEncoderDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huami_watch_opus_OpusCodecEncoder_opusEncoderDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_huami_watch_opus_OpusCodecEncoder
 * Method:    opusEncodeCtl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_huami_watch_opus_OpusCodecEncoder_opusEncodeCtl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
